name: test
on:
  workflow_dispatch:
  push:
jobs:
  default-usage:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Move test project to the working directory
        run: mv test/* .

      - name: Use this action
        uses: ./

      - name: Run build result
        run: ${{ matrix.os == 'windows' && 'build\Debug\hello_world.exe' || 'build/hello_world' }}

  specified-dir-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Use this action with specified directory
        uses: ./
        with:
          source-dir: test
          build-dir: test/build

      - name: Run build result
        run: test/build/hello_world

      - name: Check if the default build directory does not exist
        run: test ! -d build

  specified-compiler-usage:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Use this action with specified compiler
        uses: ./
        with:
          source-dir: test
          targets: test_c test_cpp
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          args: -D CHECK_USING_CLANG=ON

      - name: Run build result
        run: build/test_c && build/test_cpp

  specified-generator-usage:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Use this action with specified generator
        uses: ./
        with:
          source-dir: test
          generator: Ninja

      - name: Run build result
        run: build/hello_world
