name: test
on:
  workflow_dispatch:
  push:
jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Move test project to the working directory
        run: mv test/* .

      - name: Use this action
        uses: ./

      - name: Run build result
        run: ./build/hello_world
